layout_spectrum: 0
color:
  saturation: 0.4510961
  lightness: 0.1694772
  brandStrength: 0.9527825
  brandColors:
    - '#030303'
    - '#FBFBFB'
    - '#5C5C5C'
    - '#888888'
  rhythmicContrast: 0.7495784
typography_spectrum: 0.5210792
name: Costin
